openapi: 3.0.1
info:
  title: Lokblok Toughbox API
  description: Lokblok service API for key recovery.
  termsOfService: https://lokblok.co
  contact:
    name: Contact
    url: https://lokblok.co
  license:
    name: License
    url: https://lokblok.co
  version: 2.2.3.41755
security:
  - bearer: []
paths:
  /Login:
    $ref: paths/Login.yaml
  /GetDelegates:
    $ref: paths/GetDelegates.yaml
  /Group:
    $ref: paths/Group.yaml
  /Group/Groups:
    $ref: paths/Group_Groups.yaml
  /Group/Users:
    $ref: paths/Group_Users.yaml
  /AssignAgent:
    $ref: paths/AssignAgent.yaml
  /CreateAgent:
    $ref: paths/CreateAgent.yaml
  /AssignDelegates:
    $ref: paths/AssignDelegates.yaml
  /GetAgents:
    $ref: paths/GetAgents.yaml
  /UpdateRecoverSecret:
    $ref: paths/UpdateRecoverSecret.yaml
  /CompleteRecoverSecret:
    $ref: paths/CompleteRecoverSecret.yaml
  /EnrollSecret:
    $ref: paths/EnrollSecret.yaml
  /GetSecretStatus:
    $ref: paths/GetSecretStatus.yaml
  /StartRecoverSecret:
    $ref: paths/StartRecoverSecret.yaml
  /Toughcloud/ActivateToughcloudAccount:
    $ref: paths/Toughcloud_ActivateToughcloudAccount.yaml
  /Toughcloud/AuthorizeToughcloudAction:
    $ref: paths/Toughcloud_AuthorizeToughcloudAction.yaml
  /GetUser:
    $ref: paths/GetUser.yaml
  /AddRole:
    $ref: paths/AddRole.yaml
  /CreateUser:
    $ref: paths/CreateUser.yaml
components:
  securitySchemes:
    bearer:
      type: http
      description: Put **_ONLY_** your JWT Bearer token on textbox below!
      scheme: bearer
      bearerFormat: JWT
